DTRE\OeilBundle\Entity\User:
    attributes:
        id:
            groups: ['user', 'preference', 'auth-token']
        firstname:
            groups: ['user', 'preference', 'auth-token']
        lastname:
            groups: ['user', 'preference', 'auth-token']
        email:
            groups: ['user', 'preference', 'auth-token']
        preferences:
            groups: ['user']

DTRE\OeilBundle\Entity\AuthToken:
    attributes:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdAt:
            groups: ['auth-token']
        user:
            groups: ['auth-token']

DTRE\OeilBundle\Entity\Data:
    attributes:
        value:
            groups: ['data']
        date:
            groups: ['data']

DTRE\OeilBundle\Entity\DailyData:
    attributes:
        value:
            groups: ['dailydata']
        number:
            groups: ['dailydata']
        min:
            groups: ['dailydata']
        max:
            groups: ['dailydata']
        date:
            groups: ['dailydata']

DTRE\OeilBundle\Entity\Sensor:
    attributes:
        id:
            groups: ['sensor', 'data']
        name:
            groups: ['sensor', 'data']
        title:
            groups: ['sensor', 'data']
        subtitle:
            groups: ['sensor', 'data']
        data:
            groups: ['data']

DTRE\OeilBundle\Entity\Image:
    attributes:
        id:
            groups: ['image']
        date:
            groups: ['image']
        url:
            groups: ['image']
