DTRE\OeilBundle\Entity\User:
    attributes:
        id:
            groups: ['user', 'preference', 'auth-token', 'image', 'message']
        login:
            groups: ['user', 'preference', 'auth-token', 'image', 'message']
        mail:
            groups: ['user', 'preference', 'auth-token', 'image', 'message']
        color:
            groups: ['user', 'preference', 'auth-token', 'image', 'message']

DTRE\OeilBundle\Entity\AuthToken:
    attributes:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdAt:
            groups: ['auth-token']
        user:
            groups: ['auth-token']

DTRE\OeilBundle\Entity\Data:
    attributes:
        value:
            groups: ['data']
        date:
            groups: ['data']

DTRE\OeilBundle\Entity\DailyData:
    attributes:
        value:
            groups: ['dailydata']
        number:
            groups: ['dailydata']
        min:
            groups: ['dailydata']
        max:
            groups: ['dailydata']
        date:
            groups: ['dailydata']

DTRE\OeilBundle\Entity\Sensor:
    attributes:
        id:
            groups: ['sensor', 'data']
        name:
            groups: ['sensor', 'data']
        title:
            groups: ['sensor', 'data']
        subtitle:
            groups: ['sensor', 'data']
        data:
            groups: ['data']

DTRE\OeilBundle\Entity\Image:
    attributes:
        id:
            groups: ['image']
        date:
            groups: ['image']
        url:
            groups: ['image']
        urlth:
            groups: ['image']
        user:
            groups: ['image']

DTRE\OeilBundle\Entity\Message:
    attributes:
        id:
            groups: ['message']
        date:
            groups: ['message']
        text:
            groups: ['message']
        user:
            groups: ['message']
