DTRE\OeilBundle\Entity\User:
    attributes:
        id:
            groups: ['user', 'preference', 'auth-token']
        prenom:
            groups: ['user', 'preference', 'auth-token']
        nom:
            groups: ['user', 'preference', 'auth-token']
        mail:
            groups: ['user', 'preference', 'auth-token']

DTRE\OeilBundle\Entity\AuthToken:
    attributes:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdAt:
            groups: ['auth-token']
        user:
            groups: ['auth-token']

DTRE\OeilBundle\Entity\Data:
    attributes:
        value:
            groups: ['data']
        date:
            groups: ['data']

DTRE\OeilBundle\Entity\DailyData:
    attributes:
        value:
            groups: ['dailydata']
        number:
            groups: ['dailydata']
        min:
            groups: ['dailydata']
        max:
            groups: ['dailydata']
        date:
            groups: ['dailydata']

DTRE\OeilBundle\Entity\Sensor:
    attributes:
        id:
            groups: ['sensor']
        name:
            groups: ['sensor']
        title:
            groups: ['sensor']
        subtitle:
            groups: ['sensor']