easy_admin:
    entities:
        Sensors:
            label: 'Sensors'
            class: DTRE\OeilBundle\Entity\Sensor
        Users:
            label: 'Users'
            class: DTRE\OeilBundle\Entity\User
        Image:
            label: 'Image'
            class: DTRE\OeilBundle\Entity\Image