# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
            auth_token_user_provider:
                id: auth_token_user_provider

    firewalls:
            # disables authentication for assets and the profiler, adapt it according to your needs
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)
                security: false

            register:
                pattern: /api/users
                security: false

            main:
                pattern: ^/api/
                stateless: true
                simple_preauth:
                    authenticator: auth_token_authenticator
                provider: auth_token_user_provider
                anonymous: ~


    encoders:
        DTRE\OeilBundle\Entity\User:
            algorithm: bcrypt
            cost: 12